### ISSUE TITLE
Unnecessary replace statement

### ISSUE THREAD

**Issue by atakanyenel** [virtual-kubelet/node-cli#5]
https://github.com/virtual-kubelet/node-cli/blob/4057374acafa19e87de23e683dc74a169af899fc/go.mod#L30

This line breaks `go build` command. Probably a personal configuration.

**Comment by cpuguy83** [comment]
Sorry, don't know how I missed that.

**Comment by cpuguy83** [comment]
Fixed by https://github.com/virtual-kubelet/node-cli/commit/cd8af9b9bc8c4cf6e49994bd677165c79d498320
